title: "Ganks, Gold, and Game Outcomes"
description: "Analyzing early jungle impact in professional League of Legends matches"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

url: "https://anhpham2003.github.io"
baseurl: "/league-of-legends-jungle-impact"