title: "Ganks, Gold, and Game Outcomes"
theme: minima

# If your repo is called dsc80_finalProject and your username is anhpham2003:
url: "https://anhpham2003.github.io"
baseurl: "/league-of-legends-jungle-impact/"
